home:
    path: /
    controller: App\Controller\DefaultController::indexAction

about:
    path: /about
    controller: App\Controller\DefaultController::aboutAction

route_name:
    path: /name/{name}
    controller: App\Controller\DefaultController::nameAction